### ISSUE TITLE
Review: Landing and UserDashboard

### ISSUE THREAD

**Issue by thomasarivera** [Ube-Dev/Voluntree#73]
## Overview

The focus for this code review will be centered around the Landing page and UserDashboard component.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-73

## Files to review

* Landing.jsx
* UserDashboard.jsx

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

Monday, February 12, 11:30 AM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by aldenparoni** [comment]
## Landing.jsx

L14-L16: could we make it so that when the cursor hovers over the "Sign In" button, the color changes to white? 
L34-L36: `alt="Voluntree Logo"`, but none of these pictures are the Voluntree logo
L69: I like the color, but could we be able to change its color when we hover over these links?
L74: empty line, could be ok to delete

## UserDashboard.jsx

L19-L25: I think we can delete this if operator, and re-incorporate "ready" and LoadingSpinner into the return statement, specifically L27 and L48 like so:
```
return ready ? ( {/* display the dashboard */} ) : <LoadingSpinner />;
```

**Comment by sierranmorales** [comment]
##Landing.jsx:
	L 10, 34, 35, 36 Consider moving style to CSS file instead of inline


##UserDashboard.jsx:
	Add descriptive comments for better readability
	L 20, 24, 25 Consider moving style to CSS file instead of inline
	L 26, 27 Passing real user information instead of static values

**Comment by Jchen20-1** [comment]
## UserDashboard.jsx

* Overall comment: can maybe pass in the data into the component when its called rather than subscribing inside of the component, just to allow reusability maybe, depending on if we want to reuse this component later on, maybe with a different set of data, for example organization data. 

## Landing.jsx

* Nothing seems to be wrong.

**Comment by thomasarivera** [comment]
## Landing.jsx

L67; DE-06 - Inconsistent format. Move text to a new line.

## UserDashboard.jsx

L22; DE-05 - Unnecessary comment

**Comment by ryanseng32** [comment]
## Landing.jsx
- The spacing between all card are not very uniform.
- Calendar card bottom spacing does not line up with the upcoming events card.
- Calendar arrows could be bigger and bolder

## UserDashboard.jsx
- Having the name centered in the middle of the picture on the right side might look better.
- Possibly adding a button to the profile page right from the UserDashboard could make it easier on the user.

**Comment by jianleliu** [comment]
### UserDashboard.jsx

- Move color variables to css file
### Landing.jsx

- Looks good

**Comment by hokwaichan** [comment]
**UserDashboard.jsx**
Style can move to CSS file

**Landing.jsx**
Some text can be moved to new line

**Comment by aldenparoni** [comment]
## Outcome of meeting

New issues:
- Styling and code formatting fixes for Landing.jsx (branch a new issue)
    - Change alt for each image (L34-36)
    - Style buttons and links (all styling should be classes in style.css to put inline, not explicitly inline)
- Add "view profile" button to UserDashboard.jsx
